name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false

    steps:
    - name: Install rust
      uses: hecrj/setup-rust-action@v1
      with:
          rust-version: nightly
    - name: Install SDL2 ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
    - name: Install SDL2 macOS
      if: matrix.os == 'macos-latest'
      run: | 
           brew install SDL2
           brew install SDL2_image
           brew install SDL2_ttf
   
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
